spring.application.name=62RosasTattoo
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.datasource.url=jdbc:mariadb://localhost:3308/rosas-tattoo
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.error.include-message=always
server.error.include-binding-errors=always

#Token JWT
app.jwt.secret=Yh73kLm9xQp4zR8tV2nB6wXc5AsD9fGhJkL0pQrS
app.jwt.expiration-ms=86400000

#Admin fijo
app.admin.email=estudio@62rosastattoo.com
app.admin.password=62RosasTattoo